[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
priority-queue = "2.1.1"
strum = "0.26.3"
strum_macros = "0.26.4"
